baseURL = "https://dev.bgzona.win/"
languageCode = "bg"
title = "BG Зона - независима и неутрална България"
theme = "PaperMod"
canonifyURLs = true
relativeURLs = false

[params]
  ShowReadingTime = false
  ShowDate = false
  ShowPostNavLinks = false
  images = ["images/og-default.jpg"]

  [params.profileMode]
    enabled = false

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"

[menu]
  [[menu.main]]
    identifier = "principi"
    name = "Принципи"
    url = "/principi/"
    weight = 10

  [[menu.main]]
    identifier = "statii"
    name = "Статии"
    url = "/statii/"
    weight = 20

  [[menu.main]]
    identifier = "bezobraziya"
    name = "Безобразия"
    url = "/bezobraziya/"
    weight = 30

  [[menu.main]]
    identifier = "humor"
    name = "Хумор"
    url = "/humor/"
    weight = 40
